#!/bin/sh
# Copyright (C) 2007 Robert Gerlach <khnz@users.sourceforge.net>

read value

if [ "$value" ]; then
  if [ -w /proc/acpi/video/VGA/LCD/brightness ]; then
    if [ $value -ge 1 -a $value -le 8 ]; then
      # echo "{1..8}" > /proc/acpi/video/VGA/LCD/brightness
      echo "$value" > /proc/acpi/video/VGA/LCD/brightness
    fi
  elif [ -w /proc/acpi/video/GFX0/LCD/brightness ]; then
    if [ $value -ge 1 -a $value -le 8 ]; then
      # echo "{1 15 29 43 57 71 85 100}" > /proc/acpi/video/VGA/LCD/brightness
      value=$(( (($value - 1) * 14) + 1 ))
      if [ $value -eq 99 ]; then
        value=100
      fi
      echo "$value" > /proc/acpi/video/GFX0/LCD/brightness
    fi
  fi
fi

exit 0
