#!/bin/sh
# Copyright (C) 2007 Robert Gerlach <khnz@users.sourceforge.net>

# cat /proc/acpi/video/VGA/LCD/brightness
#  levels:  8 4 1 2 3 4 5 6 7 8 (initial 0, but max.)
#  current: 5
value="`cat /proc/acpi/video/VGA/LCD/brightness | grep current: | awk '{print $2;}'`"
if [ "$value" ]; then
	[ $value = 0 ] && value=8
	exit ${value}
else
	echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
	echo "No ACPI method found" >&2
	exit 1
fi

