#!/bin/sh
# Copyright (C) 2007 Robert Gerlach <khnz@users.sourceforge.net>

if [ -r /proc/acpi/video/VGA/LCD/brightness ]; then
  file="/proc/acpi/video/VGA/LCD/brightness"
elif [ -r /proc/acpi/video/GFX0/LCD/brightness ]; then
  file="/proc/acpi/video/GFX0/LCD/brightness"
else
  echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
  echo "No ACPI method found" >&2
  exit 1
fi

read value

# cat /proc/acpi/video/VGA/LCD/brightness
#  levels:  8 4 1 2 3 4 5 6 7 8
#  current: 4

value=`awk -F' ' '

  /^levels:/ {
    for (i=4; i<12; i++)
      levels[i-4]=$i
  }

  /^current:/ {
    print levels['$value']
  }

' $file`

echo "$value" >$file

exit 0
