#!/bin/sh
# Copyright (C) 2007 Robert Gerlach <khnz@users.sourceforge.net>

if [ "$HAL_PROP_LAPTOP_PANEL_ACCESS_METHOD" = "fjtbl" ]; then
	# cat /proc/acpi/video/VGA/LCD/brightness
	#  levels:          8 4 1 2 3 4 5 6 7 8 (initial 0, but max.)
	#  current:         5
	value="`cat /proc/acpi/video/VGA/LCD/brightness | grep current: | awk '{print $2;}'`"
	[ $value = 0 ] && value=8
else
	echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
	echo "No ACPI method found" >&2
	exit 1
fi

exit ${value}
